/*****************************************************************************
 * FileName:        TTT_Images.h
 * Description:		Holds data for images used in TicTacToe.c
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Can be AUTO-GENERATED By:  Graphics Resource Converter version: 3.3.0
 *****************************************************************************/

#ifndef TTT_IMAGES_H_FILE
#define TTT_IMAGES_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <Graphics/Graphics.h>

/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/
/*********************************
 * Bitmap Structure
 * Label: TTTX
 * Description:  60x60 pixels, 4-bits per pixel
 ***********************************/
extern const IMAGE_FLASH TTTX;
#define TTTX_WIDTH     (60)
#define TTTX_HEIGHT    (60)
#define TTTX_SIZE      (1838)
/*********************************
 * Bitmap Structure
 * Label: TTTO
 * Description:  60x60 pixels, 4-bits per pixel
 ***********************************/
extern const IMAGE_FLASH TTTO;
#define TTTO_WIDTH     (60)
#define TTTO_HEIGHT    (60)
#define TTTO_SIZE      (1838)

#endif

